server:
  port: 9009
spring:
  application:
    name: search
  rabbitmq:
    host: 10.211.55.6
    username: admin
    password: admin
    virtual-host: myvhost
  redis:
    host: 10.211.55.6
    port: 6380
    lettuce:
      pool:
        max-active: 20
        min-idle: 5
        max-wait: 150000
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  elasticsearch:
    rest:
      uris: http://10.211.55.6:9201
      connection-timeout: 60s
      read-timeout: 60s
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  client:
    config:
      default: #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 600000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 600000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: false
        isolation:
          strategy: SEMAPHORE
workerId: 0
datacenterId: 0
mall:
  thread:
    coreSize: 50
    maxSize: 200
    keepAliveTime: 200000