server:
  port: 9012
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
spring:
  application:
    name: goods
  datasource:
    username: root
    password: 990206
    url: jdbc:mysql://10.211.55.6:3308/changgou_goods?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 25
      max-active: 50
      filter:
        commons-log:
          enabled: true
  redis:
    host: 10.211.55.6
    port: 6380
    lettuce:
      pool:
        max-active: 50
        max-wait: 60000
        max-idle: 25
        min-idle: 25

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      excution:
        timeout:
          # 如果enabled设置为false,则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
  setting:
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2022-[XiaoLin](https://
workerId: 0
datacenterId: 0
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  registry:
    nacos:
      server-addr: 10.211.55.6:8848
      username: nacos
      password: nacos
    type: nacos
  config:
    type: nacos
    nacos:
      server-addr: 10.211.55.6:8848
      username: nacos
      password: nacos
